l:/nfs/user/jiaxuyang/workspace/miniconda3
l:/nfs/user/jiaxuyang/workspace/srcAna
l:/nfs/user/jiaxuyang/workspace/wenet
l:/nfs/user/jiaxuyang/workspace/configs
l:/nfs/user/jiaxuyang/workspace/kaldi
l:/nfs/user/jiaxuyang/workspace/fresh_area
n:/nfs/user/jiaxuyang/workspace
l:/nfs/user/jiaxuyang/Download/texinfo-6.0.tar.xz
l:/nfs/user/jiaxuyang/Download/flex-2.5.3.tar.gz
l:/nfs/user/jiaxuyang/Download/gcc-8.5.0.tar.gz
l:/nfs/user/jiaxuyang/Download/mpc-1.0.3.tar.gz
l:/nfs/user/jiaxuyang/Download/glibc-2.32.tar.gz
l:/nfs/user/jiaxuyang/Download/make-4.0.tar.gz
l:/nfs/user/jiaxuyang/Download/glibc-2.34.tar.gz
l:/nfs/user/jiaxuyang/Download/gcc-5.5.0.tar.gz
l:/nfs/user/jiaxuyang/Download/zsh-5.8.tar.xz
l:/nfs/user/jiaxuyang/Download/glibc-2.24.tar.gz
l:/nfs/user/jiaxuyang/Download/wenet.zip
l:/nfs/user/jiaxuyang/Download/gmp-6.1.0.tar.bz2
l:/nfs/user/jiaxuyang/Download/checkinstall-1.6.2.tar.gz
l:/nfs/user/jiaxuyang/Download/glibc-2.29.tar.gz
l:/nfs/user/jiaxuyang/Download/checkinstall-1.6.2
l:/nfs/user/jiaxuyang/Download/lf
l:/nfs/user/jiaxuyang/Download/glibc-2.3.6.tar.gz
l:/nfs/user/jiaxuyang/Download/bison-3.0.1.tar.gz
l:/nfs/user/jiaxuyang/Download/make-4.3.tar.gz
l:/nfs/user/jiaxuyang/Download/lf-linux-amd64.tar.gz
l:/nfs/user/jiaxuyang/Download/Miniconda3-py38_4.10.3-Linux-x86_64.sh
l:/nfs/user/jiaxuyang/Download/mpfr-3.1.6.tar.bz2
l:/nfs/user/jiaxuyang/Download/glibc-2.23.tar.gz
n:/nfs/user/jiaxuyang/Download
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/conf
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/wenet
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/tent.py
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/20210602_unified_transformer_server
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/check.py
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/tools
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/run.sh
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/20210618_u2pp_conformer_exp
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/loader.py
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/20210602_unified_transformer_server.tar.gz
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/local
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/raw_wav
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/zipmodel.py
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/README.md
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/tensorboard
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/path.sh
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/data
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/tmp
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/20210618_u2pp_conformer_exp.tar.gz
l:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/exp
n:/nfs/user/jiaxuyang/npm-debug.log
l:/nfs/user/jiaxuyang/usr/include
l:/nfs/user/jiaxuyang/usr/node_modules
l:/nfs/user/jiaxuyang/usr/package-lock.json
l:/nfs/user/jiaxuyang/usr/lib
l:/nfs/user/jiaxuyang/usr/share
l:/nfs/user/jiaxuyang/usr/README.md
l:/nfs/user/jiaxuyang/usr/LICENSE
l:/nfs/user/jiaxuyang/usr/etc
l:/nfs/user/jiaxuyang/usr/bin
l:/nfs/user/jiaxuyang/usr/package.json
l:/nfs/user/jiaxuyang/usr/CHANGELOG.md
n:/nfs/user/jiaxuyang/usr
n:/nfs/user/jiaxuyang/workspace/wenet/examples/lvscr/s3/
l:/nfs/user/jiaxuyang/asr-os-decoder/.git
l:/nfs/user/jiaxuyang/asr-os-decoder/batch_asr
l:/nfs/user/jiaxuyang/asr-os-decoder/demo
l:/nfs/user/jiaxuyang/asr-os-decoder/merge-cfg-tool
l:/nfs/user/jiaxuyang/asr-os-decoder/README.md
l:/nfs/user/jiaxuyang/asr-os-decoder/config
l:/nfs/user/jiaxuyang/asr-os-decoder/src
n:/nfs/user/jiaxuyang/asr-os-decoder
n:/nfs/user/jiaxuyang/.zshrc
